#!/usr/bin/env zsh

# Made by @lexisother
gitio () {
  gitio-help () {
    printf "USAGE: gitio [[%s]%s/%s] [%s]"\
           "https://github.com/"\
           "${fg[cyan]}username${reset_color}"\
           "${fg[magenta]}repo${reset_color}"\
           "${fg[green]}vanity code${reset_color}"
  }
  if [[ "$#" -eq 0 && -s ".git/config" ]]
  then
    local CONFIG_URL="$( awk '/url =/ { sub(/^.+github\.com[\/:]/, "", $3) sub(/\.git$/, "", $3) print $3 exit }' .git/config )"
  fi
  if [[ ( "$#" -eq 0 && -z "$CONFIG_URL" ) || "$1" == "-h" || "$1" == "--help" ]]
  then
    gitio-help
    return 0
  fi
  if [[ -n "$CONFIG_URL" ]]
  then
    local URL="https://github.com/$CONFIG_URL"
  elif [[ ! "$1" =~ ^(http|https)://github.com/ ]]
  then
    local URL="https://github.com/$1"
  else
    local URL="$1"
  fi
  if [[ -n "$2" ]]
  then
    local CODE="$(echo "$2" | tr "[:upper:]" "[:lower:]")"
    if [[ ! "$CODE" =~ ^[0-9a-z\-]+$ ]]
    then
      printf "Error: %s code is invalid." "${fg_bold[red]}$2${reset_color}"
      return 1
    fi
  fi
  if [[ -n "$URL" && -n "$CODE" ]]
  then
    local GITIO_URL="$( curl --include --silent https://git.io/ \
    --form url="$URL" \
    --form code="$CODE" \
    )"
  elif [[ -n "$URL" ]]
  then
    local GITIO_URL="$( curl --include --silent https://git.io/ \
      --form url="$URL" \
    )"
  else
    gitio-help return 1
  fi
  GITIO_URL="$( echo "$GITIO_URL" \
  | grep "Location: http" \
  | cut -c11- \
  | awk '{print substr($0, 1, length($0) - 1)}' \
  )"
  case "$(uname)" in
    ("Darwin") echo "$GITIO_URL" | pbcopy ;;
    ("Linux") echo "$GITIO_URL" | xclip -selection c ;;
  esac
  echo "${fg[cyan]}$GITIO_URL${reset_color}"
  xdg-open "$GITIO_URL" 2>/dev/null
}
